### PR TITLE
Add elysia adapter (with fixes)

### PR DESCRIPTION
**Pull request by kravetsone**
Merged https://github.com/felixmosh/bull-board/pull/769 https://github.com/felixmosh/bull-board/pull/850 into one

### CODE REVIEW

**Comment by kravetsone** [comment]
image

But i get type and runtime errors for `TypeError: undefined is not an object (evaluating '((_a = queue.metaValues) === null || _a === void 0 ? void 0 : _a.version).startsWith')`

What i do wrong?

**Comment by felixmosh** [comment]
It. Maybe you are on an old bullmq?

**Comment by kravetsone** [comment]
fi

> It. Maybe you are on an old bullmq?

yeah really)

**Comment by kravetsone** [comment]
image


Im getting strange errors

when i navigate to /ui page it tries to resolve ru-ru locales (but it didnt exists)

**Comment by kravetsone** [comment]
next i want to add better support/guide with https://github.com/kravetsone/jobify

thanks for the work!

**Comment by felixmosh** [comment]
> image
> 
> Im getting strange errors
> 
> when i navigate to /ui page it tries to resolve ru-ru locales (but it didnt exists)

This is expected, no locale, it fall back to English

**Comment by kravetsone** [comment]
> > image
> > Im getting strange errors
> > when i navigate to /ui page it tries to resolve ru-ru locales (but it didnt exists)
> 
> This is expected, no locale, it fall back to English

But maybe it better to check it on serverside rather than try and fail?

**Review by felixmosh — APPROVED** [review]

**Comment by felixmosh** [comment]
> > > image
> > > Im getting strange errors
> > > when i navigate to /ui page it tries to resolve ru-ru locales (but it didnt exists)
> > 
> > 
> > This is expected, no locale, it fall back to English
> 
> But maybe it better to check it on serverside rather than try and fail?

Fixed, thanx

**Comment by felixmosh** [comment]
Thank you for your contribution (and the patience).

**Comment by kravetsone** [comment]
Huh... I missed README when merge branches 

I will fix soon (for now it redirect to express)

**Comment by felixmosh** [comment]
I've fixed it.
Thank you again 🙏🏽

**Pull request merged**
