### PR TITLE
Quick glance at stats per queue

### PR DESCRIPTION
**Pull request by lukepolo**
The old version had a nice way to display stats quickly , I did a quick example of how it could look. If anyone thinks this has merit I can try to make it look better.

Quick Glance at Stats

### CODE REVIEW

**Comment by Jivings** [comment]
This looks great, is it in a working state?

**Comment by felixmosh** [comment]
In my opinion, it makes the UI cluttered and full of details. (Look at your screenshot, there many dots that has 0 jobs => redundant info).

I've thought about an `i` icon which will open on click / hover a popover with these details.
This way has 2 benefits,
1. The UI remains clean
2. You don't need to pass the stats of **all queues** on each request, it can be fetched only when the popover is open.

WDYT?

**Comment by Jivings** [comment]
I need a way to quickly see failed/waiting/complete. The other numbers are not as important. Could we add these without adding too much clutter?

I don't think an **_i_** works as well for me. I need to see at a glance if any queue is smashing failed jobs.

**Comment by felixmosh** [comment]
@Jivings how about opening a modal that will have stats of all the queues?

**Comment by lukepolo** [comment]
I’d almost rather have another view like a dashboard type of thing that we could put up on a screen , not sure others use cases

**Comment by felixmosh** [comment]
@lukepolo , an interesting idea!
Let's do it within a dashboard page

**Comment by Jivings** [comment]
Yeah that would work for me too as long as I can get to the respective queue easily from the dashboard 👍

**Comment by Deadly0** [comment]
I need this feature too. A dashboard page or an option to switch queue list to displaying queues status.

**Comment by mannharleen** [comment]
Hello hello, is there feature being added soon?

**Comment by Jivings** [comment]
I created something a bit simpler for this. The sidebar has a bar that represents the % of success/pending/failed jobs.

image

It means I can see if there are any queues that have serious problems that I need to take a closer look at. This works for me until we have a better solution.

**Pull request closed without merging**
