### PR TITLE
allow adding a route prefix to UI when using koa

### PR DESCRIPTION
**Pull request by ltjin**

### CODE REVIEW

**Comment by vcapretz** [comment]
thanks for the PR @ltjin, and sorry for the long time to review it 😅

I was a bit worried about the breaking change in the UI export, which now should be called inside the application instead of bull-board calling it, but #49 is also adding breaking changes and we can have both in a release 😄 🎉 

also, appreciate a lot you keeping the docs updated!

**Comment by vcapretz** [comment]
do you think it's worth creating an `example-koa.js` file to create a simple app using koa the way we do with express?

**Comment by vcapretz** [comment]
hey, @ltjin I just merged a big PR which now causes some conflicts in this one, can you maybe solve them so I can merge? 

thank you again for the work!

**Comment by ltjin** [comment]
I'm back to work now.
I found out that the 1.0.0-alpha.0 version using TS has been released and I will re-work on the new version.

**Comment by gabrielstuff** [comment]
hello @ltjin did you had time to work on it ? thanks !

**Comment by jvcjunior** [comment]
Any news on this one guys?

**Comment by felixmosh** [comment]
bull-board `v3.1.0` has an official koa server adapter

**Pull request closed without merging**
