### PR TITLE
feat: add addQueue and removeQueue methods

### PR DESCRIPTION
**Pull request by ejhayes**
This adds methods to add/remove queues. The current implementation currently only allows the ability to set multiple queues or replace all queues.

### CODE REVIEW

**Comment by ejhayes** [comment]
Thanks for sharing this UI @felixmosh - when you get a chance can you take a look at this PR?

**Comment by felixmosh** [comment]
@ejhayes thank you for the PR.
Will you able to fix the lint error?

**Comment by ejhayes** [comment]
Should be fixed now @felixmosh

**Comment by felixmosh** [comment]
Thank you 🙏  @ejhayes,

Your changes were published at `v2.1.0`

**Comment by ejhayes** [comment]
Wonderful, thank you @felixmosh!

**Pull request merged**
