### PR TITLE
Hide bullboard routes in fastify adapter.

### PR DESCRIPTION
**Pull request by bcomnes**
Reattempting https://github.com/felixmosh/bull-board/pull/762 with the typescript error ignored for this special case.

### CODE REVIEW

**Comment by felixmosh** [comment]
Ot still fails

**Comment by bcomnes** [comment]
It's eslint yelling about ts-ignore. I guess I'll ignore that too?

**Comment by felixmosh** [comment]
Just use as any on the type of schema obj

**Comment by felixmosh** [comment]
I've fixed it, thank you 🙏

**Comment by bcomnes** [comment]
Thank you! Sorry I ran out of time yesterday.

**Pull request closed without merging**
