### PR TITLE
Dark mode 🌙

### PR DESCRIPTION
**Pull request by difagume**
#471
Dark mode is added using [next-themes](https://github.com/pacocoursey/next-themes), a switch is added in the configuration to be able to change between light and dark, the default mode is the system mode.

### CODE REVIEW

**Comment by felixmosh** [comment]
Wow, man, this looks great!
Thank you for this PR.
I'm not sure why do we need `next-theme`?
With your permission, I would like to change some colors, is that OK by U?

**Comment by difagume** [comment]
Hi @felixmosh, now that you mention it, you're right about whether next-themes is necessary 🤔. I started by installing next-themes and creating color variables for each style module until I stopped seeing colors that clashed with dark mode. Perhaps without realizing it, I changed all the colors and next-themes might no longer be necessary.

Please feel free to make any adjustments. If you think it can help to have dark mode, I'm very happy to have been able to contribute something. 😊

**Comment by felixmosh** [comment]
image
It is not working for me...
Can you copy one of the examples and make your queue / jobs?

**Comment by felixmosh** [comment]
Progress
image
:]

**Comment by difagume** [comment]
I was reviewing it, and with the latest adjustments, it looks very good and sharper 👏

**Comment by felixmosh** [comment]
Fixed all dark mode issues in latest version.
Thank you for pushing it :)

**Pull request merged**
