### PR TITLE
Add promote all actions to delayed queues

### PR DESCRIPTION
**Pull request by Taycode**

### CODE REVIEW

**Comment by Taycode** [comment]
@felixmosh, ready for review 😄

**Comment by felixmosh** [comment]
Hi @Taycode thank you for your contribution 🙏🏼

Please format your changes with prettier...

**Comment by Taycode** [comment]
> Hi @Taycode thank you for your contribution 🙏🏼
> 
> Please format your changes with prettier...

Fixed them now @felixmosh

**Comment by felixmosh** [comment]
closes #576

**Comment by felixmosh** [comment]
Released in `v5.6.0`

**Comment by tolgap** [comment]
`bullmq` just added native support for this in v4.6.0: https://github.com/taskforcesh/bullmq/commit/6074592574256ec4b1c340126288e803e56b1a64

**Comment by felixmosh** [comment]
> `bullmq` just added native support for this in v4.6.0: [taskforcesh/bullmq@6074592](https://github.com/taskforcesh/bullmq/commit/6074592574256ec4b1c340126288e803e56b1a64)

Thanx, I will update the bullmq method 🙏🏼

**Comment by Taycode** [comment]
hmmm, thanks for notifying me. Might look towards using that instead.

Thanks again

**Pull request merged**
