### PR TITLE
Queue job count badges in menu

### PR DESCRIPTION
**Pull request by webdevian**
Under each queue name show colour coded badges for the job count of each status (if > 0)

### CODE REVIEW

**Comment by felixmosh** [comment]
Thank for this PR 🙏

Can u attach the look of it?

**Comment by webdevian** [comment]
@felixmosh Sure - 
image

The status text shows on hovering on the badge (with title attribute)

**Comment by felixmosh** [comment]
It is kinda related to the task #178
Lets make a "dashboard" page with all the stats per page... WDYT?

**Comment by webdevian** [comment]
I think it already does what that task is asking for. My inspiration for Kue-UI, we used that before switching to Bull

**Comment by felixmosh** [comment]
@webdevian as I've told in #163, I don't like this cluttered UI solution, which will fill the screen with distracting info.

Let's work on the #258 (Dashboard page) task.

**Pull request closed without merging**
