### PR TITLE
Add Job Modal

### PR DESCRIPTION
**Pull request by Diluka**
#426

- only test example.ts (Express). I'm not familiar with other adaptors
- jsoneditor's modal in modal need additional config, but I don't know how https://github.com/josdejong/jsoneditor/issues/895
- I only add enUS
- You may need replace Icon to match theme

### CODE REVIEW

**Comment by felixmosh** [comment]
I would like to make several changes.
1. move the add button to queues actions (3 dots)
2. change json editor to somthing that will allow as to specify a schema (current json editor has redandant features)
3. make all bull / bullmq add job options available (not only `attemps` & `delay`) via options json property

**Comment by Diluka** [comment]
> I would like to make several changes.
> 
> 1. move the add button to queues actions (3 dots)
> 2. change json editor to somthing that will allow as to specify a schema (current json editor has redandant features)
> 3. make all bull / bullmq add job options available (not only `attemps` & `delay`) via options json property

1. good point
2. any suggestions about the json editor? but there is no specific schema, because the data can be any form of json, even primitive values.
3. I suggest just keep the two options for now. because the official dashboard only has the two options. Leave more advanced features to other people's PRs.
4. could you please provide an icon for this button?

**Comment by felixmosh** [comment]
Sorry, I wasn't clear, I will make these changes.
Can you revert your latest 2 pushes? 
(I've made some changes based on your PR.)
I will merge it, and apply my changes over it 🙏🏽

**Comment by Diluka** [comment]
> Sorry, I wasn't clear, I will make these changes. Can you revert your latest 2 pushes? (I've made some changes based on your PR.) I will merge it, and apply my changes over it 🙏🏽

I rebased the last commit(add to header) to current(add to ...).

You can continue to rebase, even if all my commits are removed, it doesn't matter.

**Comment by felixmosh** [comment]
Can you push them (so I will merge this PR?)

some progress :]
image

**Comment by Diluka** [comment]
I rebased, so the old commit is lost. there is only new one in the branch.

If it's messed up, you can create a new branch and copy some of my codes. And close this one.  it's OK.

**Comment by felixmosh** [comment]
OK, I'll check what can be done

**Comment by Diluka** [comment]
image

Before my trial period ends, I’d better keep a screenshot of it. https://taskforce.sh

**Comment by Diluka** [comment]
Maybe to prevent the queue from being broken? These two options are safe. If options are changed incorrectly(`failParentOnFailure`, `lifo` ...), the worker may throw an exception.

The above is my guess. In fact, when I debug the queue myself, I almost never pass the job options.

**Comment by Diluka** [comment]
> Can you push them (so I will merge this PR?)
> 
> some progress :] image

I'm curious how you know what type of job data should be? I remember that there is no type information saved on the queue.

**Comment by felixmosh** [comment]
Job data is from type any... so it won't validate it.
But job options, can be validated.

**Comment by felixmosh** [comment]
Progress :]
image
Schemas are auto generated

**Comment by felixmosh** [comment]
Thank you so much for pushing this PR, it helped me to push this required feature to the lib 🙏🏽
Released in `v5.18.0` 🎊

**Comment by snird** [comment]
This is an awesome feature.
I wanted to say thank you again for your great work @Diluka @felixmosh

**Pull request merged**
