### PR TITLE
feat: add job name formatter

### LINKED ISSUE #349: Feature Request: Extract data from job to use as job Title
A few versions back, I was "abusing" the named job parameter to have better titles on the dashboard. After upgrading to the latest; when named jobs are used we get the lovely "Missing process handler" error. I'll try working on a PR to add support to make this a little more generic which can be useful for other cases.

Original named jobs method that I was abusing to accomplish this goal:
```js
await bullQueue.add(jobItem.title, jobItem)
```

---

### Proposal 1:

Append `title` parameter to `QueueOptions`, which is just a generic JSON extractor.

Example:
```js
const bullQueue = new Bull('job-queue', { title: "jobTitle" })

...

const jobItem = {
  jobTitle: item.page.title,
  url: item.page.href,
}

await bullQueue.add(jobItem)
```

---

### Proposal 2:
Append `jobTitle?` parameter to `JobOptions`, which is just a generic JSON extractor.

Example:
```js
const bullQueue = new Bull('job-queue')

...

const jobItem = {
  jobTitle: item.page.title,
  url: item.page.href,
}

await bullQueue.add(jobItem, { jobTitle: "jobTitle" })
```

---

### Expected Output:

Expected title output would be something along the lines of:
```js
`${jobName} - ${jobTitle}`
```

---

### Bonus options:

- `replace?: boolean | undefined;` - Replace entire job title for the expected output section, instead of appending `jobTitle` to `jobName`.

### PR DESCRIPTION
**Pull request by felixmosh**
closes #349

### CODE REVIEW

**Comment by bugs181** [comment]
Definitely a lot cleaner than the solution I was working on!

**Comment by bugs181** [comment]
Whoopsie. It appears that when no formatter is available, the whole `jobProps` object is passed into the `name` property. Unless I'm missing something.

**Comment by bugs181** [comment]
Fix for this:
```js
const nameProp = queue.format('name', jobProps)

return {
    name: (typeof nameProp === 'string') ? nameProp : jobProps.name,
}
```

Not the cleanest solution, but keeps the UI from crashing on my end.

**Comment by felixmosh** [comment]
Ha, you are correct :|

**Comment by bugs181** [comment]
The above fix would also take into account of the user accidentally passing the wrong info back. The `name` prop will always be guaranteed to be a string.

**Comment by felixmosh** [comment]
If a user passes a function, he "takes" responsibility to it's hand, no? ;]

**Comment by bugs181** [comment]
That is true; but sanitization and type safety is never a bad thing. Why else do we use tools like TypeScript? ;)

**Comment by felixmosh** [comment]
Yeah, I've thought about the same thing 😅
Actually, it is an easy thing to make TS check this
image

**Comment by bugs181** [comment]
Fair points. I still recommend doing something other than passing the whole `jobProps` into the `name` prop. Just for future proofing code.

**Comment by felixmosh** [comment]
I've used your suggestion, https://github.com/felixmosh/bull-board/commit/b30647767de50953b6acc9f8acfd65c67db5b1bb

**Comment by bugs181** [comment]
Very nice. Thanks for all your hard work. I hope to help contribute more in the future. Hopefully without being a thorn in your side haha.

**Pull request merged**
