### PR TITLE
Update QueueAdapterOptions typing

### PR DESCRIPTION
**Pull request by AlexisAnzieu**
Thanks for your awesome work!

Here is a typing PR to add the ability to modify one attribute only and not the whole option object.

image

### CODE REVIEW

**Comment by felixmosh** [comment]
Hi, @AlexisAnzieu thank you for wanting to contribute, but all QueueAdapters are defined with Partial<> as needed.
https://github.com/felixmosh/bull-board/blob/37a618f8cc9c58b0591f288a298293650ec2b133/packages/api/src/queueAdapters/bullMQ.ts#L13

What is the TS error that you get?

**Comment by gboudreau** [comment]
Hi @felixmosh. (I work with Alexis.)

The error is:
```
error TS2739: Type '{ readOnlyMode: true; }' is missing the following properties from type 'QueueAdapterOptions': allowRetries, prefix, description

55       options: {
         ~~~~~~~

  node_modules/@bull-board/nestjs/dist/bull-board.types.d.ts:18:5
    18     options?: QueueAdapterOptions;
           ~~~~~~~
    The expected type comes from property 'options' which is declared here on type 'BullBoardQueueOptions'
```

Our code that triggers this error:
```ts
@Module({
  // ...
  imports: [
    // ...
    BullBoardModule.forFeature({
      name: QueueName.OPENAI,
      adapter: BullAdapter,
      options: {
        readOnlyMode: true,
      },
    }),
  ],
})

**Comment by felixmosh** [comment]
Hi, thanx for the clarification, can you change the PR, so that the usage of this type will use Partial<> (inside nest module)

**Comment by felixmosh** [comment]
Released in `v5.9.2`
Thank you for your PR

**Comment by AlexisAnzieu** [comment]
Thank you for your reactivity 🚀

**Pull request merged**
