### PR TITLE
Added Queue Status to Nav

### PR DESCRIPTION
**Pull request by Slind14**
image

### CODE REVIEW

**Comment by felixmosh** [comment]
Thank you for the PR, we had many ideas on how to make these stats available, the final decision come to a Dashboard page with all of these stats #258.

I will really appreciate any help with it.

**Comment by Slind14** [comment]
We really would like this as part of the nav for UX.

**Comment by felixmosh** [comment]
The UX is not good.
I get that you need this info, but it makes the UI very clattered (a lot of noise), 
image
It is not clear what each number represents.

**Comment by Slind14** [comment]
I see. I suppose we need to work with the fork then.

**Comment by wyantb** [comment]
@felixmosh perhaps this could be defaulted to false, but available behind a configuration option passed to `createBullBoard` or similar? Call it `showsStatisticsInNavigation` or some such. I can empathize with your concern that this may not be ideal for most users, but speaking to my own operational needs this would be perfect.

**Pull request closed without merging**
