### PR TITLE
NestJS package

### PR DESCRIPTION
**Pull request by DennisSnijder**
## Context
As discussed in [#303,](https://github.com/felixmosh/bull-board/issues/303#issuecomment-1586974364)  I created a new package called `nestjs-bull-board` to easily integrate bull-board with NestJS. After some back and forth between @felixmosh and me, the library reached a state where it can be integrated into the `bull-board` mono-repo 😄 

## What has been done
- Added a new package to the mono-repo `@bull-board/nestjs`
- Added the existing package code from https://github.com/DennisSnijder/nestjs-bull-board to the new package.
- Updated documentation on the package README.md to match the new package name.

## Todo
- [X] Update the index README.md to mention the NestJS package.
- [X] Add a `with-nestjs-module` example to use the new module.

### CODE REVIEW

**Comment by DennisSnijder** [comment]
@felixmosh what do you think about the documentation location? I kept it at the README.md in the package, should we keep it there or move it over to the main README.md? 🤔

**Comment by felixmosh** [comment]
> @felixmosh what do you think about the documentation location? I kept it at the README.md in the package, should we keep it there or move it over to the main README.md? 🤔
We can add a link to the main README, to the internal README...

**Comment by DennisSnijder** [comment]
> > @felixmosh what do you think about the documentation location? I kept it at the README.md in the package, should we keep it there or move it over to the main README.md? 🤔
> 
> We can add a link to the main README, to the internal README...

Alright! i'll do that!

**Comment by DennisSnijder** [comment]
@felixmosh ready for review 😄 

When testing out the example, it depends on `@bull-board/nestjs` which isn't published yet, so the example might be broken until the package has been published to NPM.

**Comment by felixmosh** [comment]
Thank you for your contribution 🙏🏼

**Comment by felixmosh** [comment]
Can you prepare PR with the example? (don't forget to change the link in the README)

**Comment by DennisSnijder** [comment]
> Can you prepare PR with the example? (don't forget to change the link in the README)

The example is already in there! I'll test it out / update it where needed + already added a link to the Readme 😄

**Comment by felixmosh** [comment]
Thank you!

**Pull request merged**
